name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Determine Java Repository
      uses: frabert/replace-string-action@master
      id: java-repository
      with:
        pattern: '(.*)-android'
        string: "${{ github.repository }}"
        replace-with: '$1-java'
    - name: Checkout Java Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.java-repository.outputs.replaced }}
        ref: ${{ github.ref }}
        path: mgrs-java
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Build & Install Java
      run: mvn -f mgrs-java clean install -DskipTests
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build with Gradle
      run: ./gradlew build -x lint
